name: Unzip File
on:
  push:
    paths:
      - '**.zip'
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip
        run: |
          unzip -o YunzeV372-EN-h1fix.zip -d .
          rm YunzeV372-EN-h1fix.zip
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ZIP icerigi otomatik cikarildi"
          git push
